<?php

namespace FondOfSpryker\Yves\GoogleTagManageSessioneConnector;

use Spryker\Yves\Kernel\AbstractBundleDependencyProvider;
use Spryker\Yves\Kernel\Container;

class GoogleTagManageSessionConnectorDependencyProvider extends AbstractBundleDependencyProvider
{
    /**
     * @param Container $container
     *
     * @return Container
     */
    public function provideDependencies(Container $container): Container
    {
        return parent::provideDependencies($container); // TODO: Change the autogenerated stub
    }
}
